import type { FixedTextDef, LiveTextDef, TextSlotDef } from './index';

/**
 * Wording that belongs to each portrait design. The couple's names and the
 * booking date are drawn into the name and date slots. Everything else is the
 * template, until the couple writes their own wording.
 */

type Slot = Omit<TextSlotDef, 'x' | 'y' | 'maxWidth'> & { x?: number; maxWidth?: number };

function line(text: string, y: number, slot: Slot): FixedTextDef {
  return { text, x: 0.5, maxWidth: 0.82, ...slot, y };
}

function lines(texts: string[], start: number, step: number, slot: Slot): FixedTextDef[] {
  return texts.map((text, i) => line(text, start + i * step, slot));
}

const caps: Slot = { size: 0.016, font: 'glacial', colour: '#1c1c1c', letterSpacing: 0.16 };
const small: Slot = { size: 0.013, font: 'glacial', colour: '#1c1c1c', letterSpacing: 0.08 };

export const screenLive: Record<string, LiveTextDef> = {
  'cherry-blossom': {
    names: {
      layout: 'stacked',
      connector: '&',
      x: 0.5,
      y: 0.475,
      size: 0.05,
      lineHeight: 0.05,
      connectorSize: 0.03,
      font: 'brittany',
      colour: '#e7a4b8',
      maxWidth: 0.46,
    },
    date: {
      format: 'MMMM DTH YYYY',
      uppercase: true,
      x: 0.5,
      y: 0.73,
      size: 0.02,
      font: 'gotham',
      weight: 700,
      colour: '#e7a4b8',
      maxWidth: 0.7,
      letterSpacing: 0.06,
    },
    fixed: [
      line('Welcome', 0.19, { size: 0.055, font: 'brittany', colour: '#f0d2b8' }),
      line('TO THE WEDDING OF', 0.255, { size: 0.016, font: 'gotham', colour: '#f6efe8', letterSpacing: 0.2 }),
      line('ON THIS DAY', 0.69, { size: 0.014, font: 'gotham', colour: '#f6efe8', letterSpacing: 0.18 }),
      line('THANK YOU FOR', 0.78, { size: 0.016, font: 'gotham', colour: '#f6efe8', letterSpacing: 0.12 }),
      line('CELEBRATING WITH US !', 0.805, { size: 0.016, font: 'gotham', colour: '#f6efe8', letterSpacing: 0.12 }),
    ],
  },
  'pink-garden': {
    names: {
      layout: 'stacked',
      connector: '&',
      x: 0.5,
      y: 0.5,
      size: 0.058,
      lineHeight: 0.062,
      connectorSize: 0.034,
      font: 'callem',
      colour: '#c4545c',
      maxWidth: 0.36,
    },
    date: {
      format: 'DD | MM | YYYY',
      x: 0.5,
      y: 0.71,
      size: 0.02,
      font: 'gotham',
      colour: '#3a3333',
      maxWidth: 0.7,
      letterSpacing: 0.08,
    },
    fixed: [
      line('WELCOME', 0.3, { size: 0.032, font: 'gotham', weight: 700, colour: '#c4545c', letterSpacing: 0.16 }),
      line('TO OUR WEDDING', 0.345, { size: 0.016, font: 'gotham', colour: '#4a4040', letterSpacing: 0.2 }),
      line('123 Anywhere St., Any City', 0.748, { ...small, colour: '#4a4040' }),
    ],
  },
  'gilded-roses': {
    names: {
      layout: 'stacked',
      connector: '&',
      x: 0.5,
      y: 0.45,
      size: 0.074,
      lineHeight: 0.082,
      connectorSize: 0.042,
      font: 'callem',
      colour: '#f7f4ef',
      maxWidth: 0.62,
    },
    date: {
      format: 'MMMM DTH YYYY',
      uppercase: true,
      x: 0.5,
      y: 0.66,
      size: 0.02,
      font: 'gotham',
      colour: '#d4c07a',
      maxWidth: 0.7,
      letterSpacing: 0.08,
    },
    fixed: [
      line('Welcome', 0.2, { size: 0.068, font: 'callem', colour: '#f7f4ef' }),
      line('TO THE WEDDING OF', 0.27, { size: 0.015, font: 'gotham', colour: '#d4c07a', letterSpacing: 0.18 }),
      line('ON THIS DAY', 0.6, { size: 0.014, font: 'gotham', colour: '#d4c07a', letterSpacing: 0.18 }),
      line('THANK YOU FOR', 0.72, { size: 0.018, font: 'gotham', weight: 700, colour: '#f7f4ef', letterSpacing: 0.1 }),
      line('CELEBRATING WITH US !', 0.748, { size: 0.018, font: 'gotham', weight: 700, colour: '#f7f4ef', letterSpacing: 0.1 }),
    ],
  },
  'classic-charcoal': {
    names: {
      layout: 'stacked',
      connector: '&',
      connectorFont: 'signature',
      connectorSize: 0.055,
      uppercase: true,
      x: 0.5,
      y: 0.48,
      size: 0.072,
      lineHeight: 0.1,
      font: 'cinzel',
      colour: '#f4f1ea',
      maxWidth: 0.7,
      letterSpacing: 0.14,
    },
    date: {
      format: 'DD / MM / YYYY',
      x: 0.5,
      y: 0.72,
      size: 0.02,
      font: 'gotham',
      colour: '#f4f1ea',
      maxWidth: 0.7,
      letterSpacing: 0.12,
    },
    fixed: [
      line('WELCOME', 0.22, { size: 0.052, font: 'cinzel', colour: '#f4f1ea', letterSpacing: 0.32 }),
      line('TO THE WEDDING OF', 0.29, { size: 0.014, font: 'gotham', colour: '#f4f1ea', letterSpacing: 0.22 }),
      line('123 ANYWHERE ST., ANY CITY', 0.76, { size: 0.013, font: 'gotham', colour: '#f4f1ea', letterSpacing: 0.12 }),
    ],
  },
  'midnight-quote': {
    names: {
      layout: 'stacked',
      connector: '+',
      uppercase: true,
      x: 0.5,
      y: 0.62,
      size: 0.074,
      lineHeight: 0.09,
      connectorSize: 0.032,
      font: 'cinzel',
      colour: '#f7f7f7',
      maxWidth: 0.7,
      letterSpacing: 0.16,
    },
    date: {
      format: 'DD.MM.YYYY',
      x: 0.5,
      y: 0.8,
      size: 0.02,
      font: 'gotham',
      colour: '#f7f7f7',
      maxWidth: 0.7,
      letterSpacing: 0.08,
    },
    fixed: [
      ...lines(['YOUR FAVORITE', 'WEDDING QUOTE', 'GOES HERE.'], 0.14, 0.04, {
        size: 0.028,
        font: 'cinzel',
        colour: '#f7f7f7',
        letterSpacing: 0.06,
      }),
      line('Welcome', 0.38, { size: 0.04, font: 'signature', colour: '#f7f7f7' }),
      line('TO THE', 0.45, { size: 0.016, font: 'gotham', colour: '#f7f7f7', letterSpacing: 0.2 }),
      line('WEDDING OF', 0.475, { size: 0.016, font: 'gotham', colour: '#f7f7f7', letterSpacing: 0.2 }),
      line('123 ANYWHERE ST., ANY CITY', 0.845, { size: 0.013, font: 'gotham', colour: '#f7f7f7', letterSpacing: 0.1 }),
    ],
  },
  'gold-leaf-linen': {
    names: {
      layout: 'stacked',
      connector: '&',
      x: 0.5,
      y: 0.3,
      size: 0.07,
      lineHeight: 0.078,
      connectorSize: 0.04,
      font: 'callem',
      colour: '#1a1a1a',
      maxWidth: 0.7,
    },
    date: {
      format: 'D MMMM, YYYY',
      uppercase: true,
      x: 0.5,
      y: 0.8,
      size: 0.02,
      font: 'glacial',
      colour: '#1a1a1a',
      maxWidth: 0.7,
      letterSpacing: 0.08,
    },
    fixed: [
      line('WEDDING PARTY', 0.16, caps),
      line('THE CEREMONY', 0.48, caps),
      ...lines(
        [
          'THE PROCESSIONAL',
          'WELCOME MESSAGE',
          'VOWS AND RING EXCHANGE',
          'CEREMONY END',
          'FINAL BLESSING',
          'CONGRATULATIONS AND COCKTAIL HOUR',
        ],
        0.52,
        0.03,
        { ...small, maxWidth: 0.62 },
      ),
      line('123 ANYWHERE ST., ANY CITY', 0.835, { ...small, size: 0.012 }),
      line('With love', 0.89, { size: 0.032, font: 'signature', colour: '#1a1a1a' }),
    ],
  },
  'rose-quartz': {
    names: {
      layout: 'stacked',
      connector: '&',
      x: 0.5,
      y: 0.24,
      size: 0.04,
      lineHeight: 0.046,
      connectorSize: 0.026,
      font: 'callem',
      colour: '#1a1a1a',
      maxWidth: 0.7,
    },
    date: {
      format: 'D MMMM YYYY',
      uppercase: true,
      x: 0.5,
      y: 0.78,
      size: 0.016,
      font: 'glacial',
      colour: '#1a1a1a',
      maxWidth: 0.7,
      letterSpacing: 0.06,
    },
    fixed: [
      line('wedding party', 0.22, { size: 0.05, font: 'callem', colour: '#1a1a1a' }),
      ...partyList(0.3),
      line('Thank you so much for joining', 0.8, { size: 0.028, font: 'signature', colour: '#1a1a1a' }),
      line('our wedding party', 0.84, { size: 0.028, font: 'signature', colour: '#1a1a1a' }),
    ],
  },
  'blush-wildflowers': {
    names: {
      layout: 'stacked',
      connector: '&',
      x: 0.5,
      y: 0.28,
      size: 0.066,
      lineHeight: 0.074,
      connectorSize: 0.038,
      font: 'callem',
      colour: '#2a2422',
      maxWidth: 0.7,
    },
    date: {
      format: 'D MMMM, YYYY',
      uppercase: true,
      x: 0.5,
      y: 0.78,
      size: 0.018,
      font: 'glacial',
      colour: '#2a2422',
      maxWidth: 0.7,
      letterSpacing: 0.06,
    },
    fixed: [
      line('WEDDING PARTY', 0.16, { ...caps, colour: '#2a2422' }),
      ...lines(
        [
          'THE OFFICIATE',
          'DANIEL MARTHIN',
          'THE PARENTS OF THE BRIDE',
          'AGATHA PRISCILLA , LEO ROLLY',
          'THE PARENTS OF THE GROOM',
          'AGATHA PRISCILLA , LEO ROLLY',
          'MAID OF HONOR',
          'MYCHELLE AURIE',
          'BEST MAN',
          'JONATAN CHRISTIE',
        ],
        0.44,
        0.026,
        { ...small, colour: '#2a2422' },
      ),
      line('123 ANYWHERE ST., ANY CITY', 0.815, { ...small, size: 0.012, colour: '#2a2422' }),
      line('With love', 0.87, { size: 0.03, font: 'signature', colour: '#2a2422' }),
    ],
  },
  'something-blue': {
    names: {
      layout: 'stacked',
      connector: '&',
      connectorFont: 'cinzel',
      connectorSize: 0.028,
      connectorColour: '#c4a35a',
      x: 0.5,
      y: 0.29,
      size: 0.062,
      lineHeight: 0.068,
      font: 'callem',
      colour: '#3a4454',
      maxWidth: 0.72,
    },
    date: {
      format: 'D',
      x: 0.5,
      y: 0.445,
      size: 0.055,
      font: 'cinzel',
      weight: 700,
      colour: '#1a1a1a',
      maxWidth: 0.25,
    },
    moreDates: [
      {
        format: 'WEEKDAY',
        uppercase: true,
        x: 0.3,
        y: 0.445,
        size: 0.012,
        font: 'glacial',
        colour: '#243246',
        maxWidth: 0.28,
        letterSpacing: 0.14,
      },
      {
        format: 'YYYY',
        x: 0.5,
        y: 0.495,
        size: 0.014,
        font: 'cinzel',
        colour: '#1a1a1a',
        maxWidth: 0.3,
        letterSpacing: 0.12,
      },
    ],
    fixed: [
      line('WEDDING PARTY', 0.17, { ...caps, colour: '#243246' }),
      line('AT 5 PM', 0.445, { x: 0.7, size: 0.012, font: 'glacial', colour: '#243246', letterSpacing: 0.12, maxWidth: 0.28 }),
      line('THE CEREMONY', 0.56, { ...caps, colour: '#243246' }),
      ...lines(
        [
          'THE PROCESSIONAL',
          'WORDS OF WELCOME & INTRODUCTION',
          'READING & VOWS',
          'OUR FIRST KISS',
          'UNITY CEREMONY',
          'FINAL BLESSING',
          'THE RECESSIONAL',
        ],
        0.6,
        0.028,
        { ...small, colour: '#243246' },
      ),
    ],
  },
};

/** The sample wedding party on the rose quartz board. */
function partyList(start: number): FixedTextDef[] {
  const heading: Slot = { ...caps, size: 0.013, colour: '#1a1a1a' };
  const person: Slot = { ...small, size: 0.012, letterSpacing: 0.04, colour: '#1a1a1a' };
  const rows: [string, Slot][] = [
    ['THE OFFICIATE', heading],
    ['OLIVIA WILSON', person],
    ['THE PARENTS OF THE BRIDE', heading],
    ['OLIVIA WILSON , REESE MILLER', person],
    ['THE PARENTS OF THE GROOM', heading],
    ['OLIVIA WILSON , REESE MILLER', person],
    ['MAID OF HONOR', heading],
    ['REESE MILLER', person],
    ['BEST MAN', heading],
    ['REESE MILLER', person],
    ['BRIDESMAIDS', heading],
    ['REESE MILLER, OLIVIA WILSON,', person],
    ['KETUT SUSILO, REESE MILLER', person],
    ['FLOWER GIRL', heading],
    ['REESE MILLER', person],
  ];
  return rows.map(([text, slot], i) => line(text, start + i * 0.026, slot));
}
